package com.briup.bean;

public class UserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user_role.id
     *
     * @mbg.generated Mon Nov 18 09:31:02 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user_role.user_id
     *
     * @mbg.generated Mon Nov 18 09:31:02 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user_role.rold_Id
     *
     * @mbg.generated Mon Nov 18 09:31:02 CST 2019
     */
    private Integer roldId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user_role.id
     *
     * @return the value of cms_user_role.id
     *
     * @mbg.generated Mon Nov 18 09:31:02 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user_role.id
     *
     * @param id the value for cms_user_role.id
     *
     * @mbg.generated Mon Nov 18 09:31:02 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user_role.user_id
     *
     * @return the value of cms_user_role.user_id
     *
     * @mbg.generated Mon Nov 18 09:31:02 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user_role.user_id
     *
     * @param userId the value for cms_user_role.user_id
     *
     * @mbg.generated Mon Nov 18 09:31:02 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user_role.rold_Id
     *
     * @return the value of cms_user_role.rold_Id
     *
     * @mbg.generated Mon Nov 18 09:31:02 CST 2019
     */
    public Integer getRoldId() {
        return roldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user_role.rold_Id
     *
     * @param roldId the value for cms_user_role.rold_Id
     *
     * @mbg.generated Mon Nov 18 09:31:02 CST 2019
     */
    public void setRoldId(Integer roldId) {
        this.roldId = roldId;
    }
}